// <auto-generated />
using System;
using Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415143312_SeedRolesDepartmentsUsers")]
    partial class SeedRolesDepartmentsUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Name = "IT"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Name = "Operations"
                        },
                        new
                        {
                            DepartmentId = 4,
                            Name = "Customer Service"
                        },
                        new
                        {
                            DepartmentId = 5,
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "sarah.bennett@chemflow.local",
                            FirstName = "Sarah",
                            FullName = "Sarah Bennett",
                            IsActive = true,
                            JobTitle = "Head of Business Systems",
                            LastLoginAt = new DateTime(2026, 3, 21, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bennett",
                            PasswordHash = "Password123!",
                            RoleId = 1,
                            Username = "sbennett"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "james.carter@chemflow.local",
                            FirstName = "James",
                            FullName = "James Carter",
                            IsActive = true,
                            JobTitle = "IT Systems Administrator",
                            LastLoginAt = new DateTime(2026, 4, 10, 3, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Carter",
                            PasswordHash = "Password123!",
                            RoleId = 1,
                            Username = "jcarter"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "olivia.hughes@chemflow.local",
                            FirstName = "Olivia",
                            FullName = "Olivia Hughes",
                            IsActive = true,
                            JobTitle = "Account Manager",
                            LastLoginAt = new DateTime(2026, 4, 2, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hughes",
                            PasswordHash = "Password123!",
                            RoleId = 2,
                            Username = "ohughes"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 2, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "daniel.foster@chemflow.local",
                            FirstName = "Daniel",
                            FullName = "Daniel Foster",
                            IsActive = true,
                            JobTitle = "Internal Sales Executive",
                            LastLoginAt = new DateTime(2026, 4, 3, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Foster",
                            PasswordHash = "Password123!",
                            RoleId = 2,
                            Username = "dfoster"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 3, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "megan.patel@chemflow.local",
                            FirstName = "Megan",
                            FullName = "Megan Patel",
                            IsActive = true,
                            JobTitle = "Sales Coordinator",
                            LastLoginAt = new DateTime(2026, 3, 18, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patel",
                            PasswordHash = "Password123!",
                            RoleId = 2,
                            Username = "mpatel"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2024, 3, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "thomas.green@chemflow.local",
                            FirstName = "Thomas",
                            FullName = "Thomas Green",
                            IsActive = true,
                            JobTitle = "Regional Sales Representative",
                            LastLoginAt = new DateTime(2026, 3, 20, 3, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Green",
                            PasswordHash = "Password123!",
                            RoleId = 2,
                            Username = "tgreen"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2024, 3, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "rachel.morgan@chemflow.local",
                            FirstName = "Rachel",
                            FullName = "Rachel Morgan",
                            IsActive = true,
                            JobTitle = "Operations Planner",
                            LastLoginAt = new DateTime(2026, 3, 24, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morgan",
                            PasswordHash = "Password123!",
                            RoleId = 3,
                            Username = "rmorgan"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2024, 4, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "ben.turner@chemflow.local",
                            FirstName = "Ben",
                            FullName = "Ben Turner",
                            IsActive = true,
                            JobTitle = "Logistics Coordinator",
                            LastLoginAt = new DateTime(2026, 3, 23, 5, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Turner",
                            PasswordHash = "Password123!",
                            RoleId = 3,
                            Username = "bturner"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2024, 4, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "emily.scott@chemflow.local",
                            FirstName = "Emily",
                            FullName = "Emily Scott",
                            IsActive = true,
                            JobTitle = "Order Processing Specialist",
                            LastLoginAt = new DateTime(2026, 4, 9, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            PasswordHash = "Password123!",
                            RoleId = 3,
                            Username = "escott"
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2024, 5, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "nathan.price@chemflow.local",
                            FirstName = "Nathan",
                            FullName = "Nathan Price",
                            IsActive = true,
                            JobTitle = "Warehouse & Dispatch Coordinator",
                            LastLoginAt = new DateTime(2026, 4, 8, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Price",
                            PasswordHash = "Password123!",
                            RoleId = 3,
                            Username = "nprice"
                        },
                        new
                        {
                            UserId = 11,
                            CreatedAt = new DateTime(2024, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "chloe.evans@chemflow.local",
                            FirstName = "Chloe",
                            FullName = "Chloe Evans",
                            IsActive = true,
                            JobTitle = "Customer Fulfilment Analyst",
                            LastLoginAt = new DateTime(2026, 4, 3, 4, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Evans",
                            PasswordHash = "Password123!",
                            RoleId = 3,
                            Username = "cevans"
                        },
                        new
                        {
                            UserId = 12,
                            CreatedAt = new DateTime(2024, 5, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "laura.jenkins@chemflow.local",
                            FirstName = "Laura",
                            FullName = "Laura Jenkins",
                            IsActive = false,
                            JobTitle = "Former Account Manager",
                            LastName = "Jenkins",
                            PasswordHash = "Password123!",
                            RoleId = 2,
                            Username = "ljenkins"
                        },
                        new
                        {
                            UserId = 13,
                            CreatedAt = new DateTime(2024, 6, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "matthew.collins@chemflow.local",
                            FirstName = "Matthew",
                            FullName = "Matthew Collins",
                            IsActive = false,
                            JobTitle = "Former Logistics Coordinator",
                            LastName = "Collins",
                            PasswordHash = "Password123!",
                            RoleId = 3,
                            Username = "mcollins"
                        },
                        new
                        {
                            UserId = 14,
                            CreatedAt = new DateTime(2024, 6, 21, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "sophie.ward@chemflow.local",
                            FirstName = "Sophie",
                            FullName = "Sophie Ward",
                            IsActive = false,
                            JobTitle = "Former Systems Analyst",
                            LastName = "Ward",
                            PasswordHash = "Password123!",
                            RoleId = 1,
                            Username = "sward"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
