// <auto-generated />
using System;
using Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430160609_UpdateProcessingJobsForQueueSystem")]
    partial class UpdateProcessingJobsForQueueSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("County")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryInstructions")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Line2")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("AddressId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Carrier", b =>
                {
                    b.Property<int>("CarrierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarrierId"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("CarrierId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Carriers", (string)null);

                    b.HasData(
                        new
                        {
                            CarrierId = 1,
                            ContactEmail = "ops@northhaul.co.uk",
                            IsActive = true,
                            Name = "NorthHaul Logistics",
                            ServiceType = "ADR / General Haulage"
                        },
                        new
                        {
                            CarrierId = 2,
                            ContactEmail = "bookings@merseyfreight.co.uk",
                            IsActive = true,
                            Name = "Mersey Freight Partners",
                            ServiceType = "Regional Pallet and Drum Delivery"
                        },
                        new
                        {
                            CarrierId = 3,
                            ContactEmail = "orders@chemsafe-transport.co.uk",
                            IsActive = true,
                            Name = "ChemSafe Transport",
                            ServiceType = "Hazardous Goods Specialist"
                        },
                        new
                        {
                            CarrierId = 4,
                            ContactEmail = "dispatch@westline.co.uk",
                            IsActive = false,
                            Name = "WestLine Distribution",
                            ServiceType = "General Commercial Distribution"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Customers.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("BillingAddressId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("DefaultDeliveryAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndustryType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MainContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MainContactName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("MainContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentTermsDays")
                        .HasColumnType("int");

                    b.Property<int>("PricingTierId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("DefaultDeliveryAddressId");

                    b.HasIndex("PricingTierId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Customers.CustomerContact", b =>
                {
                    b.Property<int>("CustomerContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerContactId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerContactId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerContacts", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Customers.CustomerProductPrice", b =>
                {
                    b.Property<int>("CustomerProductPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerProductPriceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumOrderQuantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("OverridePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CustomerProductPriceId");

                    b.HasIndex("ProductId");

                    b.HasIndex("CustomerId", "ProductId", "EffectiveFrom");

                    b.ToTable("CustomerProductPrices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Name = "IT"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Name = "Operations"
                        },
                        new
                        {
                            DepartmentId = 4,
                            Name = "Customer Service"
                        },
                        new
                        {
                            DepartmentId = 5,
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Orders.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<int>("BillingAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<int?>("CustomerContactId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryAddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPriorityOrder")
                        .HasColumnType("bit");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("PurchaseOrderReference")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("RequestedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("AddressId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("CarrierId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerContactId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RequestedDeliveryDate");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Orders.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Orders.OrderStatusHistory", b =>
                {
                    b.Property<int>("OrderStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderStatusHistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FromStatusId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("int");

                    b.HasKey("OrderStatusHistoryId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ToStatusId");

                    b.ToTable("OrderStatusHistories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PricingTier", b =>
                {
                    b.Property<int>("PricingTierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PricingTierId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PriorityProcessing")
                        .HasColumnType("bit");

                    b.HasKey("PricingTierId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PricingTiers", (string)null);

                    b.HasData(
                        new
                        {
                            PricingTierId = 1,
                            Description = "Default commercial terms and standard processing.",
                            DiscountPercent = 0.00m,
                            Name = "Standard",
                            PriorityProcessing = false
                        },
                        new
                        {
                            PricingTierId = 2,
                            Description = "Low discount for steady-volume accounts.",
                            DiscountPercent = 3.00m,
                            Name = "Silver",
                            PriorityProcessing = false
                        },
                        new
                        {
                            PricingTierId = 3,
                            Description = "Higher discount and faster handling for key accounts.",
                            DiscountPercent = 7.50m,
                            Name = "Gold",
                            PriorityProcessing = true
                        },
                        new
                        {
                            PricingTierId = 4,
                            Description = "Priority customers with strong commercial terms.",
                            DiscountPercent = 12.00m,
                            Name = "Strategic",
                            PriorityProcessing = true
                        },
                        new
                        {
                            PricingTierId = 5,
                            Description = "Customer-specific contract pricing by product.",
                            DiscountPercent = 15.00m,
                            Name = "Contract",
                            PriorityProcessing = true
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("HazardClassId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("bit");

                    b.Property<string>("PackSize")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("RequiresSds")
                        .HasColumnType("bit");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StorageRequirement")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UNNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("HazardClassId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ProductCategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ProductCategoryId = 1,
                            Description = "Solvent-based products used in cleaning, coatings and laboratory operations.",
                            Name = "Solvents"
                        },
                        new
                        {
                            ProductCategoryId = 2,
                            Description = "Acidic products used in treatment, descaling and process control.",
                            Name = "Acids"
                        },
                        new
                        {
                            ProductCategoryId = 3,
                            Description = "Alkaline products used for cleaning, pH control and industrial operations.",
                            Name = "Alkalis"
                        },
                        new
                        {
                            ProductCategoryId = 4,
                            Description = "Products used in wastewater, potable water and process water treatment.",
                            Name = "Water Treatment"
                        },
                        new
                        {
                            ProductCategoryId = 5,
                            Description = "General industrial and specialist cleaning solutions.",
                            Name = "Cleaning Chemicals"
                        },
                        new
                        {
                            ProductCategoryId = 6,
                            Description = "Reagents and calibration liquids for lab environments.",
                            Name = "Laboratory Reagents"
                        },
                        new
                        {
                            ProductCategoryId = 7,
                            Description = "Products suitable for food and beverage environments.",
                            Name = "Food-Safe"
                        },
                        new
                        {
                            ProductCategoryId = 8,
                            Description = "Supporting consumables and handling items.",
                            Name = "Consumables"
                        },
                        new
                        {
                            ProductCategoryId = 9,
                            Description = "Additives, agents and specialist blends.",
                            Name = "Industrial Additives"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Products.HazardClass", b =>
                {
                    b.Property<int>("HazardClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HazardClassId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("HazardClassId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HazardClasses", (string)null);

                    b.HasData(
                        new
                        {
                            HazardClassId = 1,
                            Name = "Non-Hazardous"
                        },
                        new
                        {
                            HazardClassId = 2,
                            Name = "Flammable"
                        },
                        new
                        {
                            HazardClassId = 3,
                            Name = "Corrosive"
                        },
                        new
                        {
                            HazardClassId = 4,
                            Name = "Toxic"
                        },
                        new
                        {
                            HazardClassId = 5,
                            Name = "Oxidising"
                        },
                        new
                        {
                            HazardClassId = 6,
                            Name = "Irritant"
                        },
                        new
                        {
                            HazardClassId = 7,
                            Name = "Environmental Hazard"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Products.UnitOfMeasure", b =>
                {
                    b.Property<int>("UnitOfMeasureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitOfMeasureId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("UnitOfMeasureId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UnitsOfMeasure", (string)null);

                    b.HasData(
                        new
                        {
                            UnitOfMeasureId = 1,
                            Code = "L",
                            Name = "Litre"
                        },
                        new
                        {
                            UnitOfMeasureId = 2,
                            Code = "KG",
                            Name = "Kilogram"
                        },
                        new
                        {
                            UnitOfMeasureId = 3,
                            Code = "DRUM",
                            Name = "Drum"
                        },
                        new
                        {
                            UnitOfMeasureId = 4,
                            Code = "PACK",
                            Name = "Pack"
                        },
                        new
                        {
                            UnitOfMeasureId = 5,
                            Code = "BOTTLE",
                            Name = "Bottle"
                        },
                        new
                        {
                            UnitOfMeasureId = 6,
                            Code = "IBC",
                            Name = "IBC"
                        },
                        new
                        {
                            UnitOfMeasureId = 7,
                            Code = "BAG",
                            Name = "Bag"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ProjectId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProjectCode")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("Domain.Entities.SafetyDataSheet", b =>
                {
                    b.Property<int>("SafetyDataSheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SafetyDataSheetId"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SafetyDataSheetId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("SafetyDataSheets", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "sarah.bennett@chemflow.local",
                            FirstName = "Sarah",
                            FullName = "Sarah Bennett",
                            IsActive = true,
                            JobTitle = "Head of Business Systems",
                            LastLoginAt = new DateTime(2026, 3, 21, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bennett",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 1,
                            Username = "sbennett"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "james.carter@chemflow.local",
                            FirstName = "James",
                            FullName = "James Carter",
                            IsActive = true,
                            JobTitle = "IT Systems Administrator",
                            LastLoginAt = new DateTime(2026, 4, 10, 3, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Carter",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 1,
                            Username = "jcarter"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 2, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "olivia.hughes@chemflow.local",
                            FirstName = "Olivia",
                            FullName = "Olivia Hughes",
                            IsActive = true,
                            JobTitle = "Account Manager",
                            LastLoginAt = new DateTime(2026, 4, 2, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hughes",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 2,
                            Username = "ohughes"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 2, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "daniel.foster@chemflow.local",
                            FirstName = "Daniel",
                            FullName = "Daniel Foster",
                            IsActive = true,
                            JobTitle = "Internal Sales Executive",
                            LastLoginAt = new DateTime(2026, 4, 3, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Foster",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 2,
                            Username = "dfoster"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 3, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "megan.patel@chemflow.local",
                            FirstName = "Megan",
                            FullName = "Megan Patel",
                            IsActive = true,
                            JobTitle = "Sales Coordinator",
                            LastLoginAt = new DateTime(2026, 3, 18, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patel",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 2,
                            Username = "mpatel"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2024, 3, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "thomas.green@chemflow.local",
                            FirstName = "Thomas",
                            FullName = "Thomas Green",
                            IsActive = true,
                            JobTitle = "Regional Sales Representative",
                            LastLoginAt = new DateTime(2026, 3, 20, 3, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Green",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 2,
                            Username = "tgreen"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2024, 3, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "rachel.morgan@chemflow.local",
                            FirstName = "Rachel",
                            FullName = "Rachel Morgan",
                            IsActive = true,
                            JobTitle = "Operations Planner",
                            LastLoginAt = new DateTime(2026, 3, 24, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Morgan",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 3,
                            Username = "rmorgan"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2024, 4, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "ben.turner@chemflow.local",
                            FirstName = "Ben",
                            FullName = "Ben Turner",
                            IsActive = true,
                            JobTitle = "Logistics Coordinator",
                            LastLoginAt = new DateTime(2026, 3, 23, 5, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Turner",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 3,
                            Username = "bturner"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2024, 4, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "emily.scott@chemflow.local",
                            FirstName = "Emily",
                            FullName = "Emily Scott",
                            IsActive = true,
                            JobTitle = "Order Processing Specialist",
                            LastLoginAt = new DateTime(2026, 4, 9, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Scott",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 3,
                            Username = "escott"
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2024, 5, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "nathan.price@chemflow.local",
                            FirstName = "Nathan",
                            FullName = "Nathan Price",
                            IsActive = true,
                            JobTitle = "Warehouse & Dispatch Coordinator",
                            LastLoginAt = new DateTime(2026, 4, 8, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Price",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 3,
                            Username = "nprice"
                        },
                        new
                        {
                            UserId = 11,
                            CreatedAt = new DateTime(2024, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "chloe.evans@chemflow.local",
                            FirstName = "Chloe",
                            FullName = "Chloe Evans",
                            IsActive = true,
                            JobTitle = "Customer Fulfilment Analyst",
                            LastLoginAt = new DateTime(2026, 4, 3, 4, 15, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Evans",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 3,
                            Username = "cevans"
                        },
                        new
                        {
                            UserId = 12,
                            CreatedAt = new DateTime(2024, 5, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "laura.jenkins@chemflow.local",
                            FirstName = "Laura",
                            FullName = "Laura Jenkins",
                            IsActive = false,
                            JobTitle = "Former Account Manager",
                            LastName = "Jenkins",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 2,
                            Username = "ljenkins"
                        },
                        new
                        {
                            UserId = 13,
                            CreatedAt = new DateTime(2024, 6, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "matthew.collins@chemflow.local",
                            FirstName = "Matthew",
                            FullName = "Matthew Collins",
                            IsActive = false,
                            JobTitle = "Former Logistics Coordinator",
                            LastName = "Collins",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 3,
                            Username = "mcollins"
                        },
                        new
                        {
                            UserId = 14,
                            CreatedAt = new DateTime(2024, 6, 21, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "sophie.ward@chemflow.local",
                            FirstName = "Sophie",
                            FullName = "Sophie Ward",
                            IsActive = false,
                            JobTitle = "Former Systems Analyst",
                            LastName = "Ward",
                            PasswordHash = "AQAAAAIAAYagAAAAEAxPHh/D5dKq1ysW0WfcNd1UoSgMITFPlUGStQOPuEraeGeQXO+sxp+PNvm2QILaWQ==",
                            RoleId = 1,
                            Username = "sward"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("WarehouseId");

                    b.HasIndex("AddressId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("OrderStatus", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderStatusId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OrderStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            OrderStatusId = 1,
                            DisplayOrder = 1,
                            IsTerminal = false,
                            Name = "Draft"
                        },
                        new
                        {
                            OrderStatusId = 2,
                            DisplayOrder = 2,
                            IsTerminal = false,
                            Name = "Submitted"
                        },
                        new
                        {
                            OrderStatusId = 3,
                            DisplayOrder = 3,
                            IsTerminal = false,
                            Name = "Pending Review"
                        },
                        new
                        {
                            OrderStatusId = 4,
                            DisplayOrder = 4,
                            IsTerminal = false,
                            Name = "Approved"
                        },
                        new
                        {
                            OrderStatusId = 5,
                            DisplayOrder = 5,
                            IsTerminal = false,
                            Name = "In Processing"
                        },
                        new
                        {
                            OrderStatusId = 6,
                            DisplayOrder = 6,
                            IsTerminal = false,
                            Name = "Awaiting Dispatch"
                        },
                        new
                        {
                            OrderStatusId = 7,
                            DisplayOrder = 7,
                            IsTerminal = true,
                            Name = "Completed"
                        },
                        new
                        {
                            OrderStatusId = 8,
                            DisplayOrder = 8,
                            IsTerminal = true,
                            Name = "Failed"
                        },
                        new
                        {
                            OrderStatusId = 9,
                            DisplayOrder = 9,
                            IsTerminal = true,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("ProcessingJob", b =>
                {
                    b.Property<int>("ProcessingJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessingJobId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("LastRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ProcessingJobId");

                    b.HasIndex("OrderId");

                    b.ToTable("ProcessingJobs");
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.Customers.Customer", b =>
                {
                    b.HasOne("Domain.Entities.Address", "BillingAddress")
                        .WithMany()
                        .HasForeignKey("BillingAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Address", "DefaultDeliveryAddress")
                        .WithMany()
                        .HasForeignKey("DefaultDeliveryAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.PricingTier", "PricingTier")
                        .WithMany("Customers")
                        .HasForeignKey("PricingTierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingAddress");

                    b.Navigation("DefaultDeliveryAddress");

                    b.Navigation("PricingTier");
                });

            modelBuilder.Entity("Domain.Entities.Customers.CustomerContact", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", "Customer")
                        .WithMany("Contacts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.Customers.CustomerProductPrice", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", "Customer")
                        .WithMany("CustomerProductPrices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("CustomerProductPrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Orders.Order", b =>
                {
                    b.HasOne("Domain.Entities.Address", null)
                        .WithMany("Orders")
                        .HasForeignKey("AddressId");

                    b.HasOne("Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Address", "BillingAddress")
                        .WithMany("BillingOrders")
                        .HasForeignKey("BillingAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Carrier", "Carrier")
                        .WithMany("Orders")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Customers.CustomerContact", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerContactId");

                    b.HasOne("Domain.Entities.Customers.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Address", "DeliveryAddress")
                        .WithMany("DeliveryOrders")
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("Orders")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("AssignedOrders")
                        .HasForeignKey("UserId");

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("CreatedOrders")
                        .HasForeignKey("UserId1");

                    b.HasOne("Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Orders")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("BillingAddress");

                    b.Navigation("Carrier");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("OrderStatus");

                    b.Navigation("Project");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Domain.Entities.Orders.OrderItem", b =>
                {
                    b.HasOne("Domain.Entities.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Orders.OrderStatusHistory", b =>
                {
                    b.HasOne("Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Orders.Order", "Order")
                        .WithMany("OrderStatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("FromStatus");

                    b.Navigation("Order");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Products.HazardClass", "HazardClass")
                        .WithMany("Products")
                        .HasForeignKey("HazardClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Products.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("Products")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HazardClass");

                    b.Navigation("ProductCategory");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.SafetyDataSheet", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("SafetyDataSheets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "UploadedByUser")
                        .WithMany("UploadedSafetyDataSheets")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Warehouse", b =>
                {
                    b.HasOne("Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ProcessingJob", b =>
                {
                    b.HasOne("Domain.Entities.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Navigation("BillingOrders");

                    b.Navigation("DeliveryOrders");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.Carrier", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.Customers.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");

                    b.Navigation("CustomerProductPrices");

                    b.Navigation("Orders");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Domain.Entities.Customers.CustomerContact", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("OrderStatusHistory");
                });

            modelBuilder.Entity("Domain.Entities.PricingTier", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("CustomerProductPrices");

                    b.Navigation("OrderItems");

                    b.Navigation("SafetyDataSheets");
                });

            modelBuilder.Entity("Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Products.HazardClass", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Products.UnitOfMeasure", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedOrders");

                    b.Navigation("CreatedOrders");

                    b.Navigation("UploadedSafetyDataSheets");
                });

            modelBuilder.Entity("Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
