using Application.Interfaces;
using Application.Common.Exceptions;
using Application.Common.Interfaces;
using Domain.Entities;
using Domain.Entities.Documents;
using Domain.Entities.Orders;
using Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Globalization;

namespace Infrastructure.Services;

public class OrderDocumentGenerator : IOrderDocumentGenerator
{
    private const string BrandBlue = "#1CA8FE";
    private const string Ink = "#111827";
    private const string Muted = "#64748B";
    private const string Border = "#D7DEE8";
    private const string Surface = "#F8FAFC";
    private const string DocumentLogoPath = "Assets/login-logo-light.svg";
    private static readonly CultureInfo UkCulture = CultureInfo.GetCultureInfo("en-GB");

    private readonly AppDbContext _dbContext;
    private readonly IFileStorageService _fileStorage;

    public OrderDocumentGenerator(
        AppDbContext dbContext,
        IFileStorageService fileStorage)
    {
        _dbContext = dbContext;
        _fileStorage = fileStorage;
    }

    public async Task<Document> GenerateAsync(
        int orderId,
        string documentType,
        CancellationToken cancellationToken = default)
    {
        var order = await _dbContext.Orders
            .Include(o => o.Customer)
            .Include(o => o.Warehouse)
            .Include(o => o.Carrier)
            .Include(o => o.OrderItems)
                .ThenInclude(i => i.Product)
                    .ThenInclude(p => p.HazardClass)
            .Include(o => o.OrderItems)
                .ThenInclude(i => i.Product)
                    .ThenInclude(p => p.SafetyDataSheets)
            .FirstAsync(o => o.OrderId == orderId, cancellationToken);

        var safeOrderNumber = order.OrderNumber.ToLowerInvariant();
        var safeDocumentType = documentType.ToLowerInvariant();

        var fileName = $"{safeOrderNumber}_{safeDocumentType}.pdf";
        var fileKey = $"orders/{fileName}";

        var generatedPdfBytes = QuestPDF.Fluent.Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(10).FontColor(Ink));

                page.Header().Element(container => AddDocumentHeader(container, order, documentType));

                page.Content().PaddingVertical(20).Column(column =>
                {
                    column.Spacing(16);

                    AddOrderSummary(column, order);

                    if (documentType == DocumentType.SafetyDataSheetBundle)
                    {
                        AddSdsBundle(column, order);
                    }
                    else
                    {
                        AddOrderItems(column, order);
                        AddTotals(column, order);
                    }
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.DefaultTextStyle(x => x.FontSize(8).FontColor(Muted));
                    text.Span("Generated by Back. on ");
                    text.Span(FormatDateTime(DateTime.UtcNow));
                    text.Span(" UTC");
                });
            });
        })
        .GeneratePdf();

        if (documentType == DocumentType.SafetyDataSheetBundle)
        {
            var sdsFileKeys = GetSdsFileKeys(order);
            var sdsPdfs = new List<byte[]>();

            foreach (var sdsFileKey in sdsFileKeys)
            {
                sdsPdfs.Add(await _fileStorage.GetFileAsync(sdsFileKey, cancellationToken));
            }

            generatedPdfBytes = MergePdfs(generatedPdfBytes, sdsPdfs);
        }

        await _fileStorage.SaveFileAsync(fileKey, generatedPdfBytes, cancellationToken);

        var document = new Document
        {
            OrderId = order.OrderId,
            DocumentType = documentType,
            FileName = fileName,
            FilePath = fileKey,
            CreatedAt = DateTime.UtcNow,
            CreatedByUserId = null
        };

        _dbContext.Documents.Add(document);
        await _dbContext.SaveChangesAsync(cancellationToken);

        return document;
    }

    private static void AddDocumentHeader(IContainer container, Order order, string documentType)
    {
        container.Column(column =>
        {
            column.Item().Row(row =>
            {
                row.RelativeItem().Column(left =>
                {
                    var logoSvg = LoadDocumentLogoSvg();

                    if (logoSvg is not null)
                    {
                        left.Item().Width(150).Svg(logoSvg);
                    }
                    else
                    {
                        left.Item().Text(text =>
                        {
                            text.Span("Back").FontSize(28).Bold().FontColor(Colors.Black);
                            text.Span(".").FontSize(28).Bold().FontColor(BrandBlue);
                        });
                    }
                });

                row.ConstantItem(220).AlignRight().Column(right =>
                {
                    right.Item().AlignRight().Text(FormatDocumentTitle(documentType))
                        .FontSize(18)
                        .SemiBold()
                        .FontColor(Ink);

                    right.Item().AlignRight().PaddingTop(4).Text(order.OrderNumber)
                        .FontSize(11)
                        .FontColor(Muted);
                });
            });

            column.Item().PaddingTop(18).Height(2).Background(BrandBlue);
        });
    }

    private static void AddOrderSummary(ColumnDescriptor column, Order order)
    {
        AddSectionTitle(column, "Order Details");

        column.Item().Border(1).BorderColor(Border).Background(Surface).Padding(14).Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn();
                columns.RelativeColumn();
            });

            AddRow(table, "Customer", order.Customer?.CompanyName ?? $"Customer #{order.CustomerId}");
            AddRow(table, "Warehouse", order.Warehouse?.Name ?? "—");
            AddRow(table, "Carrier", order.Carrier?.Name ?? "—");
            AddRow(table, "Created", FormatDateTime(order.CreatedAt));
            AddRow(table, "Requested Delivery", FormatDate(order.RequestedDeliveryDate));
            AddRow(table, "Priority", order.IsPriorityOrder ? "Yes" : "No");
        });
    }

    private static void AddSdsBundle(ColumnDescriptor column, Order order)
    {
        AddSectionTitle(column, "Safety Data Sheet Bundle");

        var sdsItems = order.OrderItems
            .Where(i => i.DeletedAt == null && i.Product.RequiresSds)
            .GroupBy(i => i.ProductId)
            .Select(g => g.First())
            .ToList();

        var missingSdsProducts = sdsItems
            .Select(i => i.Product)
            .Where(p => !p.SafetyDataSheets.Any(s => s.IsActive && s.DeletedAt == null))
            .Select(p => $"{p.ProductName} ({p.SKU})")
            .ToList();

        if (missingSdsProducts.Count > 0)
        {
            throw new InvalidOperationException(
                $"Cannot generate SDS bundle. Missing active SDS for: {string.Join(", ", missingSdsProducts)}.");
        }

        column.Item()
            .Border(1)
            .BorderColor(Border)
            .Background(Surface)
            .Padding(14)
            .Text("This bundle contains the active safety data sheets for the order products that require safety documentation.")
            .FontColor(Ink);

        column.Item().Border(1).BorderColor(Border).Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(2.4f);
                columns.RelativeColumn(1.4f);
                columns.RelativeColumn();
                columns.RelativeColumn(1.5f);
                columns.RelativeColumn(1.4f);
            });

            table.Header(header =>
            {
                AddHeaderCell(header.Cell(), "Product");
                AddHeaderCell(header.Cell(), "Hazard Class");
                AddHeaderCell(header.Cell(), "UN Number");
                AddHeaderCell(header.Cell(), "Storage");
                AddHeaderCell(header.Cell(), "SDS");
            });

            foreach (var item in sdsItems)
            {
                var product = item.Product;

                var activeSds = product.SafetyDataSheets
                    .Where(s => s.IsActive && s.DeletedAt == null)
                    .OrderByDescending(s => s.EffectiveDate)
                    .First();

                AddBodyCell(table.Cell(), $"{product.ProductName}\n{product.SKU}");
                AddBodyCell(table.Cell(), product.HazardClass?.Name ?? "Not specified");
                AddBodyCell(table.Cell(), string.IsNullOrWhiteSpace(product.UNNumber) ? "Not specified" : product.UNNumber);
                AddBodyCell(table.Cell(), string.IsNullOrWhiteSpace(product.StorageRequirement) ? "Not specified" : product.StorageRequirement);
                AddBodyCell(table.Cell(), $"{activeSds.FileName}\nVersion {activeSds.Version}\nEffective {FormatDate(activeSds.EffectiveDate)}");
            }
        });
    }

    private static void AddOrderItems(ColumnDescriptor column, Order order)
    {
        AddSectionTitle(column, "Order Items");

        column.Item().Border(1).BorderColor(Border).Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(5);
                columns.ConstantColumn(60);
                columns.ConstantColumn(90);
                columns.ConstantColumn(100);
            });

            table.Header(header =>
            {
                AddHeaderCell(header.Cell(), "Product");
                AddHeaderCell(header.Cell().AlignRight(), "Qty");
                AddHeaderCell(header.Cell().AlignRight(), "Unit");
                AddHeaderCell(header.Cell().AlignRight(), "Line Total");
            });

            foreach (var item in order.OrderItems)
            {
                AddBodyCell(table.Cell(), item.Product?.ProductName ?? $"Product #{item.ProductId}");
                AddBodyCell(table.Cell().AlignRight(), item.Quantity.ToString());
                AddBodyCell(table.Cell().AlignRight(), FormatMoney(item.UnitPrice, order.Currency));
                AddBodyCell(table.Cell().AlignRight(), FormatMoney(item.LineTotal, order.Currency));
            }
        });
    }

    private static void AddTotals(ColumnDescriptor column, Order order)
    {
        column.Item().AlignRight().Width(220).Border(1).BorderColor(Border).Padding(12).Column(totals =>
        {
            totals.Spacing(6);

            AddTotalRow(totals, "Subtotal", FormatMoney(order.Subtotal, order.Currency));
            AddTotalRow(totals, "Discount", FormatMoney(order.DiscountAmount, order.Currency));
            AddTotalRow(totals, "Tax", FormatMoney(order.TaxAmount, order.Currency));

            totals.Item().BorderTop(1).BorderColor(Border).PaddingTop(8).Row(row =>
            {
                row.RelativeItem().Text("Total")
                    .SemiBold()
                    .FontSize(12);

                row.ConstantItem(110).AlignRight().Text(FormatMoney(order.TotalAmount, order.Currency))
                    .FontSize(12)
                    .SemiBold();
            });
        });
    }

    private static void AddSectionTitle(ColumnDescriptor column, string title)
    {
        column.Item().Text(title)
            .FontSize(13)
            .SemiBold()
            .FontColor(Ink);
    }

    private static void AddHeaderCell(IContainer cell, string value)
    {
        cell.Background(Surface)
            .BorderRight(1)
            .BorderBottom(1)
            .BorderColor(Border)
            .PaddingHorizontal(8)
            .PaddingVertical(7)
            .Text(value)
            .SemiBold()
            .FontColor(Ink);
    }

    private static void AddBodyCell(IContainer cell, string value)
    {
        cell.BorderRight(1)
            .BorderBottom(1)
            .BorderColor(Border)
            .PaddingHorizontal(8)
            .PaddingVertical(7)
            .Text(value)
            .FontColor(Ink);
    }

    private static void AddTotalRow(ColumnDescriptor totals, string label, string value)
    {
        totals.Item().Row(row =>
        {
            row.RelativeItem().Text(label).FontColor(Muted);
            row.ConstantItem(110).AlignRight().Text(value).FontColor(Ink);
        });
    }

    private static string FormatDocumentTitle(string documentType)
    {
        return documentType switch
        {
            DocumentType.OrderSummary => "Order Summary",
            DocumentType.SafetyDataSheetBundle => "SDS Bundle",
            _ => documentType
        };
    }

    private static string FormatMoney(decimal amount, string currency)
    {
        var symbol = currency.Equals("GBP", StringComparison.OrdinalIgnoreCase)
            ? "£"
            : $"{currency} ";

        return $"{symbol}{amount:0.00}";
    }

    private static string? LoadDocumentLogoSvg()
    {
        var path = Path.Combine(AppContext.BaseDirectory, DocumentLogoPath);

        return File.Exists(path)
            ? File.ReadAllText(path)
            : null;
    }

    private static string FormatDate(DateTime? value)
    {
        return value.HasValue
            ? value.Value.ToString("dd MMM yyyy", UkCulture)
            : "—";
    }

    private static string FormatDateTime(DateTime value)
    {
        return value.ToString("dd MMM yyyy, HH:mm", UkCulture);
    }

    private static void AddRow(TableDescriptor table, string label, string value)
    {
        table.Cell().PaddingVertical(4).Text(label).SemiBold().FontColor(Muted);
        table.Cell().PaddingVertical(4).Text(value).FontColor(Ink);
    }

    private List<string> GetSdsFileKeys(Order order)
    {
        var sdsItems = order.OrderItems
            .Where(i => i.DeletedAt == null && i.Product.RequiresSds)
            .GroupBy(i => i.ProductId)
            .Select(g => g.First())
            .ToList();

        var fileKeys = new List<string>();
        var missingFiles = new List<string>();

        foreach (var item in sdsItems)
        {
            var activeSds = item.Product.SafetyDataSheets
                .Where(s => s.IsActive && s.DeletedAt == null)
                .OrderByDescending(s => s.EffectiveDate)
                .FirstOrDefault();

            if (activeSds == null)
            {
                missingFiles.Add($"{item.Product.ProductName} ({item.Product.SKU})");
                continue;
            }

            if (string.IsNullOrWhiteSpace(activeSds.FilePath))
            {
                missingFiles.Add($"{item.Product.ProductName} ({item.Product.SKU}) - {activeSds.FileName}");
                continue;
            }

            if (!_fileStorage.FileExists(activeSds.FilePath))
            {
                missingFiles.Add($"{item.Product.ProductName} ({item.Product.SKU}) - {activeSds.FileName}");
                continue;
            }

            fileKeys.Add(activeSds.FilePath);
        }

        if (missingFiles.Count > 0)
        {
            throw new OperatorActionRequiredException(
                $"Cannot generate SDS bundle. SDS PDF file missing for: {string.Join(", ", missingFiles)}.");
        }

        return fileKeys
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static byte[] MergePdfs(byte[] mainPdfBytes, List<byte[]> pdfsToAppend)
    {
        using var outputDocument = new PdfSharpCore.Pdf.PdfDocument();

        using (var mainStream = new MemoryStream(mainPdfBytes))
        using (var mainDocument = PdfSharpCore.Pdf.IO.PdfReader.Open(
            mainStream,
            PdfSharpCore.Pdf.IO.PdfDocumentOpenMode.Import))
        {
            foreach (var page in mainDocument.Pages)
            {
                outputDocument.AddPage(page);
            }
        }

        foreach (var pdfBytes in pdfsToAppend)
        {
            using var sdsStream = new MemoryStream(pdfBytes);
            using var sdsDocument = PdfSharpCore.Pdf.IO.PdfReader.Open(
                sdsStream,
                PdfSharpCore.Pdf.IO.PdfDocumentOpenMode.Import);

            foreach (var page in sdsDocument.Pages)
            {
                outputDocument.AddPage(page);
            }
        }

        using var outputStream = new MemoryStream();
        outputDocument.Save(outputStream);
        return outputStream.ToArray();
    }
}
