using Domain.Entities.Documents;
using Domain.Entities.Orders;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Globalization;

namespace Infrastructure.Services.Documents;

internal class OrderDocumentPdfBuilder
{
    private const string BrandBlue = "#1CA8FE";
    private const string Ink = "#111827";
    private const string Muted = "#64748B";
    private const string Border = "#D7DEE8";
    private const string Surface = "#F8FAFC";
    private const float TableBorderWidth = 1.5f;
    private const string DocumentLogoPath = "Assets/login-logo-light.svg";
    private static readonly CultureInfo UkCulture = CultureInfo.GetCultureInfo("en-GB");

    public byte[] Build(Order order, string documentType)
    {
        return QuestPDF.Fluent.Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(10).FontColor(Ink));

                page.Header().Element(container => AddDocumentHeader(container, order, documentType));

                page.Content().PaddingVertical(20).Column(column =>
                {
                    column.Spacing(16);

                    AddOrderSummary(column, order);

                    if (documentType == DocumentType.SafetyDataSheetBundle)
                    {
                        AddSdsBundle(column, order);
                    }
                    else
                    {
                        AddOrderItems(column, order);
                        AddTotals(column, order);
                    }
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.DefaultTextStyle(x => x.FontSize(8).FontColor(Muted));
                    text.Span("Generated by Back. on ");
                    text.Span(FormatDateTime(DateTime.UtcNow));
                    text.Span(" UTC");
                });
            });
        })
        .GeneratePdf();
    }

    private static void AddDocumentHeader(IContainer container, Order order, string documentType)
    {
        container.Column(column =>
        {
            column.Item().Row(row =>
            {
                row.RelativeItem().Column(left =>
                {
                    var logoSvg = LoadDocumentLogoSvg();

                    if (logoSvg is not null)
                    {
                        left.Item().Width(150).Svg(logoSvg);
                    }
                    else
                    {
                        left.Item().Text(text =>
                        {
                            text.Span("Back").FontSize(28).Bold().FontColor(Colors.Black);
                            text.Span(".").FontSize(28).Bold().FontColor(BrandBlue);
                        });
                    }
                });

                row.ConstantItem(220).AlignRight().Column(right =>
                {
                    right.Item().AlignRight().Text(FormatDocumentTitle(documentType))
                        .FontSize(18)
                        .SemiBold()
                        .FontColor(Ink);

                    right.Item().AlignRight().PaddingTop(4).Text(order.OrderNumber)
                        .FontSize(11)
                        .FontColor(Muted);
                });
            });

            column.Item().PaddingTop(18).Height(2).Background(BrandBlue);
        });
    }

    private static void AddOrderSummary(ColumnDescriptor column, Order order)
    {
        AddSectionTitle(column, "Order Details");

        column.Item().Border(1).BorderColor(Border).Background(Surface).Padding(14).Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn();
                columns.RelativeColumn();
            });

            AddRow(table, "Customer", order.Customer?.CompanyName ?? $"Customer #{order.CustomerId}");
            AddRow(table, "Warehouse", order.Warehouse?.Name ?? "—");
            AddRow(table, "Carrier", order.Carrier?.Name ?? "—");
            AddRow(table, "Created", FormatDateTime(order.CreatedAt));
            AddRow(table, "Requested Delivery", FormatDate(order.RequestedDeliveryDate));
            AddRow(table, "Priority", order.IsPriorityOrder ? "Yes" : "No");
        });
    }

    private static void AddSdsBundle(ColumnDescriptor column, Order order)
    {
        AddSectionTitle(column, "Safety Data Sheet Bundle");

        var sdsProducts = order.GetProductsRequiringSafetyDataSheets();

        column.Item()
            .Border(1)
            .BorderColor(Border)
            .Background(Surface)
            .Padding(14)
            .Text("This bundle contains the active safety data sheets for the order products that require safety documentation.")
            .FontColor(Ink);

        column.Item().Border(TableBorderWidth).BorderColor(Border).Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(2.4f);
                columns.RelativeColumn(1.4f);
                columns.RelativeColumn();
                columns.RelativeColumn(1.5f);
                columns.RelativeColumn(1.4f);
            });

            table.Header(header =>
            {
                AddHeaderCell(header.Cell(), "Product");
                AddHeaderCell(header.Cell(), "Hazard Class");
                AddHeaderCell(header.Cell(), "UN Number");
                AddHeaderCell(header.Cell(), "Storage");
                AddHeaderCell(header.Cell(), "SDS");
            });

            foreach (var product in sdsProducts)
            {
                var activeSds = product.SafetyDataSheets
                    .Where(s => s.IsActive && s.DeletedAt == null)
                    .OrderByDescending(s => s.EffectiveDate)
                    .First();

                AddBodyCell(table.Cell(), $"{product.ProductName}\n{product.SKU}");
                AddBodyCell(table.Cell(), product.HazardClass?.Name ?? "Not specified");
                AddBodyCell(table.Cell(), string.IsNullOrWhiteSpace(product.UNNumber) ? "Not specified" : product.UNNumber);
                AddBodyCell(table.Cell(), string.IsNullOrWhiteSpace(product.StorageRequirement) ? "Not specified" : product.StorageRequirement);
                AddBodyCell(table.Cell(), $"{activeSds.FileName}\nVersion {activeSds.Version}\nEffective {FormatDate(activeSds.EffectiveDate)}");
            }
        });
    }

    private static void AddOrderItems(ColumnDescriptor column, Order order)
    {
        AddSectionTitle(column, "Order Items");

        column.Item().Border(TableBorderWidth).BorderColor(Border).Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(5);
                columns.ConstantColumn(60);
                columns.ConstantColumn(90);
                columns.ConstantColumn(100);
            });

            table.Header(header =>
            {
                AddHeaderCell(header.Cell(), "Product");
                AddHeaderCell(header.Cell(), "Qty", alignRight: true);
                AddHeaderCell(header.Cell(), "Unit", alignRight: true);
                AddHeaderCell(header.Cell(), "Line Total", alignRight: true);
            });

            foreach (var item in order.OrderItems)
            {
                AddBodyCell(table.Cell(), item.Product?.ProductName ?? $"Product #{item.ProductId}");
                AddBodyCell(table.Cell(), item.Quantity.ToString(), alignRight: true);
                AddBodyCell(table.Cell(), FormatMoney(item.UnitPrice, order.Currency), alignRight: true);
                AddBodyCell(table.Cell(), FormatMoney(item.LineTotal, order.Currency), alignRight: true);
            }
        });
    }

    private static void AddTotals(ColumnDescriptor column, Order order)
    {
        column.Item().AlignRight().Width(220).Border(1).BorderColor(Border).Padding(12).Column(totals =>
        {
            totals.Spacing(6);

            AddTotalRow(totals, "Subtotal", FormatMoney(order.Subtotal, order.Currency));
            AddTotalRow(totals, "Discount", FormatMoney(order.DiscountAmount, order.Currency));
            AddTotalRow(totals, "Tax", FormatMoney(order.TaxAmount, order.Currency));

            totals.Item().BorderTop(1).BorderColor(Border).PaddingTop(8).Row(row =>
            {
                row.RelativeItem().Text("Total")
                    .SemiBold()
                    .FontSize(12);

                row.ConstantItem(110).AlignRight().Text(FormatMoney(order.TotalAmount, order.Currency))
                    .FontSize(12)
                    .SemiBold();
            });
        });
    }

    private static void AddSectionTitle(ColumnDescriptor column, string title)
    {
        column.Item().Text(title)
            .FontSize(13)
            .SemiBold()
            .FontColor(Ink);
    }

    private static void AddHeaderCell(IContainer cell, string value, bool alignRight = false)
    {
        StyleTableCell(cell, Surface)
            .Text(text =>
            {
                if (alignRight)
                {
                    text.AlignRight();
                }

                text.Span(value)
                    .SemiBold()
                    .FontColor(Ink);
            });
    }

    private static void AddBodyCell(IContainer cell, string value, bool alignRight = false)
    {
        StyleTableCell(cell, Colors.White)
            .Text(text =>
            {
                if (alignRight)
                {
                    text.AlignRight();
                }

                text.Span(value).FontColor(Ink);
            });
    }

    private static IContainer StyleTableCell(IContainer cell, string background)
    {
        return cell
            .BorderRight(TableBorderWidth)
            .BorderBottom(TableBorderWidth)
            .BorderColor(Border)
            .Background(background)
            .PaddingHorizontal(8)
            .PaddingVertical(7);
    }

    private static void AddTotalRow(ColumnDescriptor totals, string label, string value)
    {
        totals.Item().Row(row =>
        {
            row.RelativeItem().Text(label).FontColor(Muted);
            row.ConstantItem(110).AlignRight().Text(value).FontColor(Ink);
        });
    }

    private static void AddRow(TableDescriptor table, string label, string value)
    {
        table.Cell().PaddingVertical(4).Text(label).SemiBold().FontColor(Muted);
        table.Cell().PaddingVertical(4).Text(value).FontColor(Ink);
    }

    private static string FormatDocumentTitle(string documentType)
    {
        return documentType switch
        {
            DocumentType.OrderSummary => "Order Summary",
            DocumentType.SafetyDataSheetBundle => "SDS Bundle",
            _ => documentType
        };
    }

    private static string FormatMoney(decimal amount, string currency)
    {
        var symbol = currency.Equals("GBP", StringComparison.OrdinalIgnoreCase)
            ? "£"
            : $"{currency} ";

        return $"{symbol}{amount:0.00}";
    }

    private static string? LoadDocumentLogoSvg()
    {
        var path = Path.Combine(AppContext.BaseDirectory, DocumentLogoPath);

        return File.Exists(path)
            ? File.ReadAllText(path)
            : null;
    }

    private static string FormatDate(DateTime? value)
    {
        return value.HasValue
            ? value.Value.ToString("dd MMM yyyy", UkCulture)
            : "—";
    }

    private static string FormatDateTime(DateTime value)
    {
        return value.ToString("dd MMM yyyy, HH:mm", UkCulture);
    }
}
